; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Simple Sale POS"
#ifndef MyAppVersion
#define MyAppVersion "0.0.0"
#endif
#define MyAppPublisher "SimpleSale Team"
#define MyAppURL "https://simplesale.uz"
#define MyAppExeName "simple_sale.exe"
#define MyAppIconName "runner\resources\app_icon.ico"

[Setup]
; AppId is uniquely identified for this application.
AppId={{D3E6B22C-4A3C-4C6E-9F1B-4A3D1E2C3D4E}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; Output info
OutputDir=..\build\windows\x64\runner\Release\installer
OutputBaseFilename=SimpleSale_Setup
SetupIconFile={#MyAppIconName}
Compression=lzma
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=admin
ArchitecturesAllowed=x64
ArchitecturesInstallIn64BitMode=x64

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "..\build\windows\x64\runner\Release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\windows\x64\runner\Release\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; Include VC++ redist if needed
Source: "vc_redist.x64.exe"; DestDir: "{tmp}"; Flags: deleteafterinstall

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon; IconFilename: "{app}\{#MyAppExeName}"

[InstallDelete]
; Clean up existing shortcuts from both possible locations before creating the new one
Type: files; Name: "{userdesktop}\{#MyAppName}.lnk"
Type: files; Name: "{commondesktop}\{#MyAppName}.lnk"
Type: files; Name: "{userprograms}\{#MyAppName}.lnk"
Type: files; Name: "{commonprograms}\{#MyAppName}.lnk"

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

; Add Firewall rule for the application during installation
Filename: "{sys}\netsh.exe"; \
    Parameters: "advfirewall firewall add rule name=""Simple Sale POS"" dir=in action=allow program=""{app}\{#MyAppExeName}"" enable=yes"; \
    Flags: runhidden; StatusMsg: "Tarmoq sozlamalari yangilanmoqda..."
Filename: "{sys}\netsh.exe"; \
    Parameters: "advfirewall firewall add rule name=""Simple Sale Sync"" dir=in action=allow protocol=TCP localport=8080 enable=yes"; \
    Flags: runhidden; StatusMsg: "Sinxronizatsiya porti ochilmoqda..."

[UninstallDelete]
; Delete the database file from Documents (Old location)
Type: files; Name: "{userdocs}\simple_sale.db"
; Delete the backup folder if exists
Type: filesandordirs; Name: "{userdocs}\SimpleSaleBackups"

; Delete Application Data folders (Shared Preferences, Cache, etc.)
; Using both organization names to be absolutely sure
Type: filesandordirs; Name: "{userappdata}\Simple Sale Solutions\{#MyAppName}"
Type: filesandordirs; Name: "{localappdata}\Simple Sale Solutions\{#MyAppName}"
Type: filesandordirs; Name: "{userappdata}\com.example\{#MyAppName}"
Type: filesandordirs; Name: "{localappdata}\com.example\{#MyAppName}"
Type: filesandordirs; Name: "{userappdata}\SimpleSale"
Type: filesandordirs; Name: "{localappdata}\SimpleSale"

[Registry]
; Clean up registry settings on uninstall (Shared Preferences and App configs)
Root: HKCU; Subkey: "Software\Simple Sale Solutions\{#MyAppName}"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\com.example\simple_sale"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\simple_sale"; Flags: uninsdeletekey
